version = 0.1

[default.deploy.parameters]
stack_name = "kandidat-70-sam"
resolve_s3 = true
s3_prefix = "kandidat-70-sam"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"kandidat-70-data\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
